In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Social_Network_Ads.csv')

df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
gender = pd.get_dummies(df['Gender'], drop_first= True)

gender.head()

Male
0     1
1     1
2     0
3     0
4     1

In [4]:
df1 = pd.concat([df,gender], axis = 1)
df1.head()

User ID  Gender  Age  EstimatedSalary  Purchased  Male
0  15624510    Male   19            19000          0     1
1  15810944    Male   35            20000          0     1
2  15668575  Female   26            43000          0     0
3  15603246  Female   27            57000          0     0
4  15804002    Male   19            76000          0     1

In [5]:
df1.drop(['User ID','Gender'], axis= 1, inplace= True)

In [6]:
df1.head()

Age  EstimatedSalary  Purchased  Male
0   19            19000          0     1
1   35            20000          0     1
2   26            43000          0     0
3   27            57000          0     0
4   19            76000          0     1

In [7]:
x = df1[['Age','EstimatedSalary','Male']]
x.shape

(400, 3)

In [8]:
y = df1['Purchased']
y.shape

(400,)

In [9]:
x

Age  EstimatedSalary  Male
0     19            19000     1
1     35            20000     1
2     26            43000     0
3     27            57000     0
4     19            76000     1
..   ...              ...   ...
395   46            41000     0
396   51            23000     1
397   50            20000     0
398   36            33000     1
399   49            36000     0

[400 rows x 3 columns]

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.25, random_state= 0)

### Feature scaling.... Standard_scaler

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()

In [13]:
x_train = scaler.fit_transform(x_train)

x_train

array([[ 0.58164944, -0.88670699, -0.98019606],
       [-0.60673761,  1.46173768,  1.02020406],
       [-0.01254409, -0.5677824 , -0.98019606],
       [-0.60673761,  1.89663484, -0.98019606],
       [ 1.37390747, -1.40858358, -0.98019606],
       [ 1.47293972,  0.99784738, -0.98019606],
       [ 0.08648817, -0.79972756,  1.02020406],
       [-0.01254409, -0.24885782,  1.02020406],
       [-0.21060859, -0.5677824 , -0.98019606],
       [-0.21060859, -0.19087153, -0.98019606],
       [-0.30964085, -1.29261101, -0.98019606],
       [-0.30964085, -0.5677824 ,  1.02020406],
       [ 0.38358493,  0.09905991,  1.02020406],
       [ 0.8787462 , -0.59677555, -0.98019606],
       [ 2.06713324, -1.17663843, -0.98019606],
       [ 1.07681071, -0.13288524,  1.02020406],
       [ 0.68068169,  1.78066227, -0.98019606],
       [-0.70576986,  0.56295021, -0.98019606],
       [ 0.77971394,  0.35999821, -0.98019606],
       [ 0.8787462 , -0.53878926, -0.98019606],
       [-1.20093113, -1.58254245,  1.020

In [14]:
x_test = scaler.transform(x_test)

x_test

array([[-0.80480212,  0.50496393,  1.02020406],
       [-0.01254409, -0.5677824 , -0.98019606],
       [-0.30964085,  0.1570462 ,  1.02020406],
       [-0.80480212,  0.27301877, -0.98019606],
       [-0.30964085, -0.5677824 , -0.98019606],
       [-1.10189888, -1.43757673,  1.02020406],
       [-0.70576986, -1.58254245, -0.98019606],
       [-0.21060859,  2.15757314,  1.02020406],
       [-1.99318916, -0.04590581, -0.98019606],
       [ 0.8787462 , -0.77073441,  1.02020406],
       [-0.80480212, -0.59677555,  1.02020406],
       [-1.00286662, -0.42281668, -0.98019606],
       [-0.11157634, -0.42281668,  1.02020406],
       [ 0.08648817,  0.21503249,  1.02020406],
       [-1.79512465,  0.47597078,  1.02020406],
       [-0.60673761,  1.37475825, -0.98019606],
       [-0.11157634,  0.21503249,  1.02020406],
       [-1.89415691,  0.44697764,  1.02020406],
       [ 1.67100423,  1.75166912, -0.98019606],
       [-0.30964085, -1.37959044,  1.02020406],
       [-0.30964085, -0.65476184, -0.980

## Random Forest Classifier

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
r_classifier = RandomForestClassifier(n_estimators= 10, criterion= 'entropy', random_state= 50)
                                   ## n_estimators => it means the number of Decision Tree we required
                                 ## criterion => entropy or gini_impurity

In [17]:
r_classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=50)

In [18]:
y_pred = r_classifier.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[64,  4],
       [ 5, 27]], dtype=int64)

In [21]:
score = accuracy_score(y_test, y_pred)

score

0.91

# RandomizedSearchCV....... HyperParameter tunning

In [28]:
from sklearn.model_selection import RandomizedSearchCV

In [29]:
from scipy.stats import randint

In [30]:
est = RandomForestClassifier(n_jobs= -1)

In [31]:
forest_para = {'max_depth': [3,5,10,None], 
               'n_estimators': [10,20,50,100,200,300,500], 
               'max_features' : randint(1,2), 
              'criterion': ['gini', 'entropy'], 
               'bootstrap':[True, False],
               'min_samples_leaf' : randint(1,4)}

In [32]:
def hypertuning_rscv(est, para_dict, num_iter, x, y):
    
    random_search = RandomizedSearchCV(est, 
                                       param_distributions= para_dict, 
                                       n_jobs= -1,
                                       n_iter= num_iter, cv =10)
    
     #CV = Cross-Validation ( here using Stratified KFold CV)
    
    random_search.fit(x,y)
    
    hyper_para = random_search.best_params_
    
    hyper_score = random_search.best_score_
    
    return hyper_para, hyper_score

In [33]:
rforest_para, rforest_score = hypertuning_rscv(est, forest_para, 40, x, y)

In [34]:
rforest_para

{'bootstrap': True,
 'criterion': 'gini',
 'max_depth': 3,
 'max_features': 1,
 'min_samples_leaf': 2,
 'n_estimators': 200}

In [35]:
rforest_score                   ## this is the RandomSearchCV accuracy score

0.9075

### Use the above parameters in the random forest classifier

In [36]:
classifier = RandomForestClassifier(n_estimators= 200,
                                    bootstrap= True,
                                    criterion= 'gini',
                                    max_depth= 3,
                                    max_features= 1,
                                    min_samples_leaf= 2)

In [37]:
classifier.fit(x_train, y_train)

RandomForestClassifier(max_depth=3, max_features=1, min_samples_leaf=2,
                       n_estimators=200)

In [38]:
y_pred = classifier.predict(x_test)

In [39]:
metrix = confusion_matrix(y_test, y_pred)

metrix

array([[64,  4],
       [ 3, 29]], dtype=int64)

In [40]:
a_score = accuracy_score(y_test, y_pred)

a_score

0.93

In [41]:
from sklearn.model_selection import cross_val_score

In [43]:
cross_val = cross_val_score(classifier,x_train,y_train,cv=10,scoring='accuracy').mean()

cross_val

0.8966666666666667

In [44]:
cross_val = cross_val_score(classifier,x_test,y_test,cv=10,scoring='accuracy').mean()

cross_val

0.93

In [45]:
cross_val = cross_val_score(classifier, x, y, cv=10, scoring='accuracy').mean()

cross_val

0.9049999999999999